apiVersion : v1
kind	   : ConfigMap
data:
  nginx.key: |
    -----BEGIN PRIVATE KEY-----
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDF+zys3xeadfL8
    oOFArKpC94SXbO/RIx79NbJcR+yeqy9dYYglnCynzV6PGxX8FHfv6H1L+I5FACW6
    P0DSr5MvArlSzMYKYGfTKe1eeuwK5msHiRfa7hn8a8ihBGjMLQlkPbr3rYyyQynn
    M+G/woo3IWLwRcAgVE2m11jPL8Vhwp3GEmVjY+zqNGibGLbb9KFu+CLpsv8TDK9R
    t34oMEnZww5VNnOFf3QR5W7P7mlQpESD1DjOT2VZ8wMk1562ICgG1BswHTPVNCVh
    C+wS4fMCOfR6yJ8SEn0zZ4Ab+jIJpwHDtCRoDymvcq7gY0KTnLb27xSVkPssXw5N
    L5wdxYAvAgMBAAECggEAXCZcT3pnWhWcS8n2DkxP02ux42lpFkbqnaDoq9suX4v+
    N9C1tgvDHTeR07ofuX0tdhUYfMvsLGGtLctTOL1QHImACPIXG61Tpg3V1iwQweIN
    3ywIVnaM0di5QXjz7lToEihJZg75dd+dGWgko0TBYHfBvWQ50NJsckO5qnXpwV4p
    5rnrFksvmZAmqf0HFgBaLvmLhYnRULjxUJP1iubQiRpx4zJYYcBsK1kdj5BUmOh9
    qPji2d/Q24GMQhV3MPPdBMi0BqkI2fMBgaWloZvNThERCeET1ZGOwkMhaDkrRIJw
    5OT4Zh2r7vTBidqZVtQRXB/tVwsdfkTYUDLphay3gQKBgQD3C+omZkVvC9q1MzfW
    KQ+3RbsB35pbWKMbS0/unjtn8b2+/XD2f95h588oP1a4NXFnBfqTsWWlnxNkJuDq
    SuNTTRDnyMhMCd8Yw20sRR/AARHbbO6JuSN3DJYcG2kenkeYJf2ZoHzlbxA92IFb
    2BxjLhsJ2UBp8ctgpNPepMAYNwKBgQDNKBkxFtkFUI4zjkA0qfgulMOFFXcL1ssL
    7Aq5PdoQs+Vk2Nf9FpvI0TfWXssVzc/qKyW/it0ry6NVG+SiPNGxztz5q29cuZNC
    BOL33u8fyYMlP6asn1ElAN5ifzxidhEmjM/gSdYxnYALqbgdPLKuBG/KoHLFHY2l
    08UiLQjryQKBgDxHfPenprOEyfXCrJIl7L7EVfAMFkbJpurHApbvpwEi3DCY+JI8
    +w8al9JzOf6yk5wWumCFPY8e9IVQczrX0QYHXOOhezYKhpQtQxs1Np0L5caLmtyh
    /wRSXuI20fx1lHSMeIeewDrfUbA1fsLhRXPx0QkjKHNxWzWWolfGDVUbAoGBAJ0k
    hL9UJ+FpRbL51/Y+5woPCwBqY6he22KDZ+diGCFJGoG3kyGZ6rPUhbefHmHSJtrQ
    N/bSj/zW24H6fpNCkMBomlxnU0KsJr6f7ZY9Xd50RQ8IBUweMFJuqui5WvB0TUjA
    /Q1ooTeZ05WbZ5qFfrvKTDLh2Wdg7rnBTzORWU75AoGAKDCGaEgAZIQ0CsT2Ae+W
    YE1hbgdHRhY7yqwaO8VjjnSAvspS/0PBoxcpfQGCKMf08EkahSaQ3iSkV4lsnW9L
    1yfi97/IN1/NWfgnD1YiIUGh5oyKqOXnvg5Pwyw8d/rPb3vdJ90C6uew+r1gBcG0
    Og2osfbs2EH6MbisuaFJanc=
    -----END PRIVATE KEY-----
metadata:
  creationTimestamp: null
  name: nginx-key-bb
---
apiVersion : v1
kind       : ConfigMap
data:
  nginx.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDtDCCApygAwIBAgIJAInce9H6/fX1MA0GCSqGSIb3DQEBCwUAMG8xCzAJBgNV
    BAYTAlNMMRMwEQYDVQQIDApLbm93LVdoZXJlMQ4wDAYDVQQHDAVUZXJyYTERMA8G
    A1UECgwIU3RhckxvcmQxEjAQBgNVBAsMCUd1YXJkaWFuczEUMBIGA1UEAwwLKi5r
    OHMubG9jYWwwHhcNMTgwMzMxMDkwMTAxWhcNMTkwMzMxMDkwMTAxWjBvMQswCQYD
    VQQGEwJTTDETMBEGA1UECAwKS25vdy1XaGVyZTEOMAwGA1UEBwwFVGVycmExETAP
    BgNVBAoMCFN0YXJMb3JkMRIwEAYDVQQLDAlHdWFyZGlhbnMxFDASBgNVBAMMCyou
    azhzLmxvY2FsMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxfs8rN8X
    mnXy/KDhQKyqQveEl2zv0SMe/TWyXEfsnqsvXWGIJZwsp81ejxsV/BR37+h9S/iO
    RQAluj9A0q+TLwK5UszGCmBn0yntXnrsCuZrB4kX2u4Z/GvIoQRozC0JZD26962M
    skMp5zPhv8KKNyFi8EXAIFRNptdYzy/FYcKdxhJlY2Ps6jRomxi22/Shbvgi6bL/
    EwyvUbd+KDBJ2cMOVTZzhX90EeVuz+5pUKREg9Q4zk9lWfMDJNeetiAoBtQbMB0z
    1TQlYQvsEuHzAjn0esifEhJ9M2eAG/oyCacBw7QkaA8pr3Ku4GNCk5y29u8UlZD7
    LF8OTS+cHcWALwIDAQABo1MwUTAdBgNVHQ4EFgQUtO9TDCWGAtP0Ix6miVOjlUmv
    w78wHwYDVR0jBBgwFoAUtO9TDCWGAtP0Ix6miVOjlUmvw78wDwYDVR0TAQH/BAUw
    AwEB/zANBgkqhkiG9w0BAQsFAAOCAQEARGNG6o/5xi25p2/y/DxxVZ/LKwc1IBn1
    kFV8lIRHn2g+mwj4iKHTnQa+lfTZu5pGwe9WjbcBYaC7wlNd6qwfN1wDuixugZUm
    1RbKpkx0CgwQZIu8mmswf5KcNs6sZva2YuKkgTku63+drhGq6DaLYkkASjoz9Nvj
    pQ7oRldmBnrPATPNrvm0WQAsdYuz/zJGzw9pKVkHfj0zimdHO+jbJ95UpX5Ih4l6
    SOFO885Hr+orRZK+s78QvJ9wKqqW6X9DeFCU2LGFsr4YOBxTNoTuRl1+/s0tFyWb
    tc8RRWqVzzDnMtn0HMRqwYLLzbcLcNV6EYAIRwj9g0ArdhLWxil7ew==
    -----END CERTIFICATE-----
metadata:
  creationTimestamp: null
  name: nginx-cert-bb
---
apiVersion : v1
kind       : ConfigMap
data:
  myconf.conf: |
    server {
            listen 80 default_server;
            listen [::]:80 default_server ipv6only=on;

            listen 443 ssl;

            root /usr/share/nginx/html;
            index index.html index.htm;

            server_name test.k8s.local;
            ssl_certificate /etc/ssl/certs/nginx.crt;
            ssl_certificate_key /etc/ssl/keys/nginx.key;

            location / {
                   proxy_pass http://my-emp ;
            }
    }
metadata:
  creationTimestamp: null
  name: nginx-default-bb
